apiVersion: v1
kind: Service
metadata:
  name: demo-app-svc
  namespace: {{ .Values.namespaceOverride | default .Release.Namespace }}
  labels:
    app: demo-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: demo-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
